version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: telegram-bot-postgres
    environment:
      POSTGRES_DB: telegramflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d telegramflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - telegram-bot-network

  # Telegram Bot Application
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot-app
    env_file: ./.env
    environment:
      # Override DATABASE_URL for Docker networking
      DATABASE_URL: postgresql://postgres:1234@postgres:5432/telegramflow
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - telegram-bot-network
    volumes:
      # Mount assets directory for persistent file storage
      - ./src/assets:/app/src/assets:ro
    healthcheck:
      test:
        - CMD-SHELL
        - "pg_isready -h localhost -U postgres -d telegramflow"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  postgres_data:
    driver: local

networks:
  telegram-bot-network:
    driver: bridge 